safe_mode:
  boot_is_good_after: 1min
  reboot_timeout: 5min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway_ip
    subnet: !secret subnet_mask
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret ap_password

captive_portal:

debug:

# Enable OTA
ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: sntp
    timezone: Europe/Amsterdam
    servers:
      - 0.nl.pool.ntp.org
      - 1.nl.pool.ntp.org
      - 2.nl.pool.ntp.org
    update_interval: 60s

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  include_internal: false
  local: ${local}
  log: true
  version: 3

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Diagnostics
sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    name: "Signaalsterkte"
    update_interval: 5s
    unit_of_measurement: "dBm"
    device_class: signal_strength
    state_class: measurement
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_strength
    name: "Signaalniveau"
    icon: mdi:signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    state_class: measurement
    entity_category: diagnostic

  - platform: uptime
    id: uptime_seconds
    update_interval: 1min
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_sensor
            state: !lambda |-
              int seconds = round(id(uptime_seconds).raw_state);
              int days = seconds / 86400;
              seconds %= 86400;
              int hours = seconds / 3600;
              seconds %= 3600;
              int minutes = seconds / 60;
              seconds %= 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "u " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: debug
    reset_reason:
      name: "Herstartreden"
      icon: mdi:information
      entity_category: diagnostic
  
  - platform: wifi_info
    dns_address:
      name: "DNS-adres"
      icon: mdi:dns
      entity_category: diagnostic
    ip_address:
      name: "IP-adres"
      icon: mdi:ip
      entity_category: diagnostic
    ssid:
      name: "SSID"
      icon: mdi:wifi
      entity_category: diagnostic
    power_save_mode:
      name: "WiFi-energiebesparingsmodus"
      icon: mdi:wifi-arrow-left-right
      entity_category: diagnostic

  - platform: template
    id: uptime_sensor
    name: "Uptime"
    icon: mdi:clock-time-four-outline
    entity_category: diagnostic

button:
  - platform: restart
    id: restart_button
    name: "Herstarten"
    entity_category: diagnostic
    on_press:
      then:
        - switch.turn_off: relay
        - delay: 2s
        - switch.turn_on: relay

  - platform: safe_mode
    name: "Herstarten (veilige modus)"
    entity_category: diagnostic
